export const environment = {
  production: false,
  /*  banner: 'https://banner-services.firebaseio.com',*/
  mockBanner: '/api/carousel',
  featuresBanner: '/api/features',
  popularProductMilk: '/api/productMilk',
  popularProductCoffee: '/api/productCoffee',
  popularProductPet: '/api/productPet',
  popularProductMeat: '/api/productMeat',
  popularProductVegetable: '/api/productVegetable',
  popularProductFruit: '/api/productFruit',
  dealsOfTheDay: '/api/dealsDay',
  topSelling: '/api/topSell',
  trendingProducts: '/api/trendProduct',
  recentAdded: '/api/recentAdded',
  topRatedProduct: '/api/topRatedProduct',
  dailyFeaturedProduct: '/api/dailyFeaturedProduct',
  dailyPopularProduct: '/api/dailyPopularProduct',
  dailyNewAddedProduct: '/api/dailyNewAddedProduct',
  categoryHeaderMenu: '/api/categoryHeaderMenu',
  footerBottomMenu: '/api/footerBottomMenu',
  headerTopSmartMenu: '/api/headerTopSmartMenu',
  headerTopInfoMessage: '/api/headerTopInfoMessage',
  addCard: '/api/addCard',
};
